import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

export default [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    /*
      next-env.d.ts is generated by next and carries a triple-slash path
      reference the TypeScript rules reject. The file says not to edit it, and
      next rewrites it every build, so it is excluded rather than fought with.

      CI runs lint before build, so today the file is absent and the error never
      fires — this stops that ordering from being load-bearing.
    */
    ignores: [".next/**", "node_modules/**", "next-env.d.ts"],
  },
];
