/// <reference types="next" />
/// <reference types="next/image-types/global" />

/*
  Committed on purpose.

  next-env.d.ts carries these same references, but it is generated by `next
  build`/`next dev` and is gitignored — so in CI, where `tsc --noEmit` runs
  before any next command, it does not exist. Without the image-types
  reference a static import of a .png resolves to no module at all and
  typecheck fails on a file that is perfectly correct locally.

  This file is checked in so typecheck stands on its own rather than depending
  on a build having happened first. Editing next-env.d.ts instead would not
  work: Next rewrites it.
*/
